image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade && 
    flutter update-packages --force-upgrade &&
    flutter run -d web-server --no-resident # prebuilds the app
  command: >
    flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
ports:
- port: 8080
  onOpen: open-preview
- command: |
    mkdir -p /home/gitpod/.android
    touch /home/gitpod/.android/repositories.cfg
    export PATH=/usr/lib/dart/bin:$FLUTTER_HOME/bin:$ANDROID_HOME/bin:$PATH
    /home/gitpod/android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
vscode:
  extensions:
    - Dart-Code.dart-code@3.24.1
    - Dart-Code.flutter@3.24.0